name: project-1-initial-setup
on: 
  schedule:
    - cron: '*/5 * * * *' # every 5 mins
jobs:
  just-some-commands:
    runs-on: 
      labels: homelab
    steps:
      - uses: actions/checkout@v3
      - run: ip addr; whoami